version: "3.8"
services:
  # MySQL service
  mysql-toronto-time:
    image: mysql:8.0
    container_name: mysql-toronto-time
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Replace with your actual password
      MYSQL_DATABASE: toronto_time
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql  # Persists MySQL data

  # Go application service
  go-toronto-time-app:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure the correct Dockerfile is used
    container_name: go-toronto-time-app
    depends_on:
      - mysql-toronto-time  # Ensure MySQL starts before the Go app
    environment:
      MYSQL_PASSWORD: rootpassword  # Your MySQL password
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
