version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-toronto-time
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}  # Use the password from the .env file
      MYSQL_DATABASE: toronto_time
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  go-app:
    build: .
    container_name: go-toronto-time
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # Ensure the Go app uses the same password
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    restart: always

volumes:
  mysql-data:
